# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    container: appiriodev/dx-cli-dev:20200330-152812.125810

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Run ADX docker image
      - name: Run ADX
        run: adx

      # Runs a single command using the runners shell
      - name: Deploy To SIT
        env:
          ADX_REFRESH_TOKEN: ${{ secrets.ADX_REFRESH_TOKEN }}
        run: |
          adx deploy:source --sourcepath force-app/main/default --targetalias SIT

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
